#!/usr/bin/env bash
#
# Initialize Berachain from scratch (beacond + bera-reth).
#
# Snapshot flow — skip this script; restore snapshots into:
#   $HOME/berachain-beacond-data
#   $HOME/berachain-reth-data
# then: ./create-jwt.sh && ./run-setup-initialisation.sh && docker compose up -d
#
# From-scratch flow uses committed chain params under config/:
#   genesis.json, kzg-trusted-setup.json
# app.toml, config.toml, client.toml are generated by `beacond init`.
#
# Usage: ./init-database.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

ENV_FILE="${SCRIPT_DIR}/.env"
GENESIS_FILE="${SCRIPT_DIR}/config/genesis.json"
KZG_FILE="${SCRIPT_DIR}/config/kzg-trusted-setup.json"
BEACOND_HOME="${BEACOND_HOME:-${HOME}/berachain-beacond-data}"
RETH_DATA="${RETH_DATA:-${HOME}/berachain-reth-data}"
BEACOND_CONFIG="${BEACOND_HOME}/config"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "ERROR: ${ENV_FILE} not found (cp env.template .env first)." >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "${ENV_FILE}"
set +a

for var in BEACON_KIT_IMAGE BERA_RETH_IMAGE MONIKER_NAME; do
  if [[ -z "${!var:-}" ]]; then
    echo "ERROR: ${var} is not set in .env" >&2
    exit 1
  fi
done

for tool in docker; do
  command -v "${tool}" >/dev/null 2>&1 || {
    echo "ERROR: '${tool}' is required." >&2
    exit 1
  }
done

for required in "${GENESIS_FILE}" "${KZG_FILE}"; do
  if [[ ! -f "${required}" ]]; then
    echo "ERROR: missing ${required}" >&2
    exit 1
  fi
done

if [[ -f "${BEACOND_CONFIG}/priv_validator_key.json" ]]; then
  echo "WARNING: ${BEACOND_HOME} already contains beacond config."
  read -r -p "Wipe and re-initialize? (y/N): " ans
  case "${ans}" in
    y|Y) rm -rf "${BEACOND_HOME}" ;;
    *) echo "Aborted."; exit 0 ;;
  esac
fi

if [[ -d "${RETH_DATA}/db" || -d "${RETH_DATA}/rocksdb" ]]; then
  echo "WARNING: ${RETH_DATA} already contains reth chain data."
  read -r -p "Wipe and re-initialize? (y/N): " ans
  case "${ans}" in
    y|Y) rm -rf "${RETH_DATA}" ;;
    *) echo "Aborted."; exit 0 ;;
  esac
fi

mkdir -p "${BEACOND_HOME}" "${RETH_DATA}"

echo "==> Initializing beacond (generates app.toml, config.toml, client.toml)"
docker run --rm \
  -v "${BEACOND_HOME}:/root/.beacond" \
  "${BEACON_KIT_IMAGE}" \
  init "${MONIKER_NAME}" \
  --beacon-kit.chain-spec=mainnet \
  --home /root/.beacond

for generated in app.toml config.toml client.toml priv_validator_key.json node_key.json; do
  if [[ ! -f "${BEACOND_CONFIG}/${generated}" ]]; then
    echo "ERROR: beacond init did not create ${BEACOND_CONFIG}/${generated}" >&2
    exit 1
  fi
done

echo "==> Installing committed genesis and KZG trusted setup"
cp "${GENESIS_FILE}" "${BEACOND_CONFIG}/genesis.json"
cp "${KZG_FILE}" "${BEACOND_CONFIG}/kzg-trusted-setup.json"

echo "==> Initializing bera-reth datadir"
docker run --rm \
  -v "${RETH_DATA}:/data" \
  --entrypoint reth \
  "${BERA_RETH_IMAGE}" \
  init --datadir /data --chain mainnet

echo "==> Generating JWT and patching docker networking settings"
"${SCRIPT_DIR}/create-jwt.sh"
NONINTERACTIVE=1 "${SCRIPT_DIR}/run-setup-initialisation.sh"

echo ""
echo "==> Initialization complete"
echo "    beacond: ${BEACOND_HOME}"
echo "    reth:    ${RETH_DATA}"
echo "Next: docker compose up -d"
