networks:
  xlayer-network:
    name: xlayer-network

services:
  op-geth:
    image: "${OP_GETH_IMAGE_TAG}"
    container_name: xlayer-mainnet-op-geth
    entrypoint: geth
    ports:
      - "127.0.0.1:28545:8545"   # HTTP RPC
      - "127.0.0.1:28546:7546"     # WebSocket
      - "35303:35303" # P2P TCP
      - "35303:35303/udp" # P2P UDP
    volumes:
      - ${HOME}/xlayer-op-geth-data:/data
      - ./config/jwt.txt:/jwt.txt
      - ./config/op-geth-config-mainnet.toml:/config.toml
      - ./logs-mainnet/op-geth:/var/log/op-geth
    command:
      - --verbosity=3
      - --datadir=/data
      - --config=/config.toml
      - --db.engine=pebble
      - --gcmode=archive
      - --rollup.enabletxpooladmission
      - --rollup.sequencerhttp=https://rpc.xlayer.tech
      - --log.file=/var/log/op-geth/geth.log
      - --pp-rpc-url=${X_LAYER_PP_RPC_URL}
      - --port=35303
      - --nat=extip:${EXT_IP}
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8545"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 3s
    stop_grace_period: 120s
    networks:
      - xlayer-network

  op-node:
    image: "${OP_STACK_IMAGE_TAG}"
    container_name: xlayer-mainnet-op-node
    entrypoint: sh
    networks:
      - xlayer-network
    ports:
      - "127.0.0.1:9555:9545"
    volumes:
      - ${HOME}/xlayer-op-node-data:/data
      - ./config/rollup-mainnet.json:/rollup.json
      - ./config/jwt.txt:/jwt.txt
      - ./logs-mainnet/op-node:/var/log/op-node
    command:
      - -c
      - |
        exec /app/op-node/bin/op-node \
          --log.level=info \
          --l2=http://op-geth:8552 \
          --l2.jwt-secret=/jwt.txt \
          --sequencer.enabled=false \
          --verifier.l1-confs=1 \
          --rollup.config=/rollup.json \
          --rpc.addr=0.0.0.0 \
          --rpc.port=9545 \
          --p2p.listen.tcp=9233 \
          --p2p.listen.udp=9233 \
          --p2p.peerstore.path=/data/p2p/opnode_peerstore_db \
          --p2p.discovery.path=/data/p2p/opnode_discovery_db \
          --p2p.bootnodes=enode://c67d7f63c5483ab8311123d2997bfe6a8aac2b117a40167cf71682f8a3e37d3b86547c786559355c4c05ae0b1a7e7a1b8fde55050b183f96728d62e276467ce1@8.210.177.150:9223,enode://28e3e305b266e01226a7cc979ab692b22507784095157453ee0e34607bb3beac9a5b00f3e3d7d3ac36164612ca25108e6b79f75e3a9ecb54a0b3e7eb3e097d37@8.210.15.172:9223,enode://b5aa43622aad25c619650a0b7f8bb030161dfbfd5664233f92d841a33b404cea3ffffdc5bc8d6667c7dc212242a52f0702825c1e51612047f75c847ab96ef7a6@8.210.69.97:9223 \
          --p2p.static=/ip4/47.242.38.0/tcp/9223/p2p/16Uiu2HAmH1AVhKWR29mb5s8Cubgsbh4CH1G86A6yoVtjrLWQgiY3,/ip4/8.210.153.12/tcp/9223/p2p/16Uiu2HAkuerkmQYMZxYiQYfQcPob9H7XHPwS7pd8opPTMEm2nsAp,/ip4/8.210.117.27/tcp/9223/p2p/16Uiu2HAmQEzn2WQj4kmWVrK9aQsfyQcETgXQKjcKGrTPsKcJBv7a \
          --rpc.enable-admin=true \
          --l1=${L1_RPC_URL} \
          --l1.beacon=${L1_BEACON_URL} \
          --l1.rpckind=standard \
          --conductor.enabled=false \
          --safedb.path=/data/safedb \
          2>&1 | tee /var/log/op-node/op-node.log
    depends_on:
      - op-geth

  # X Layer CDK Erigon (archival backend for op-geth pp-rpc-url)
  xlayer-cdk-erigon:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        XERIGON_REF: ${ERIGON_VERSION}
    image: xlayer-cdk-erigon:${ERIGON_VERSION}
    container_name: xlayer-cdk-erigon
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    stop_grace_period: 120s
    volumes:
      - ${HOME}/xlayer-cdk-erigon-data:${DATADIR}
      - "./xlayer.yaml:/app/config/xlayer.yaml:ro"
    command:
      - "--config=/app/config/xlayer.yaml"
      - --zkevm.l1-rpc-url=${ZKEVM_L1_RPC_URL}
      - --nodiscover
      - --maxpeers=0
      - --zkevm.increment-tree-always=true
      - --zkevm.sync-limit=0
      - --zkevm.sequencer-paused=true
      - --zkevm.executor-enabled=false
      - --zkevm.l1-contract-address-retrieve=false
      - --zkevm.l1-contract-address-check=false
      - --zkevm.l1-sync-start-block=0
      - --zkevm.l1-sync-stop-batch=1
      - --debug.no-sync=true
    networks:
      - xlayer-network
