services:
  mode-op-reth:
    image: ${OP_RETH_IMAGE}
    container_name: mode-op-reth
    entrypoint: ["op-reth"]
    command:
      - node
      - --chain=mode
      - --datadir=/data
      - --rollup.sequencer=https://rpc-mode-mainnet-0.t.conduit.xyz
      - --rollup.disable-tx-pool-gossip
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3,debug,trace,txpool
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=eth,net,web3,debug,trace,txpool
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/config/jwt.hex
      - --rpc.gascap=${GAS_CAP}
      - --nat=extip:${EXT_IP}
      - --port=${P2P_PORT}
      - --discovery.addr=0.0.0.0
      - --discovery.port=${P2P_PORT}
      - --discovery.v5.port=${P2P_PORT}
      - --rpc-cache.max-concurrent-db-requests=2048
      - --rpc-cache.max-blocks=5000
      - --rpc.max-connections=2000
    volumes:
      - ${HOST_DATADIR:-$HOME/mode-op-reth-data}:/data
      - ./config:/config
    ports:
      - ${RPC_BIND_ADDR}:${HTTP_PORT}:8545
      - ${RPC_BIND_ADDR}:${WS_PORT}:8546
      - ${P2P_PORT}:${P2P_PORT}
      - ${P2P_PORT}:${P2P_PORT}/udp
    restart: unless-stopped
    stop_grace_period: 120s
    networks:
      - mode-network

  mode-op-node:
    image: ${OP_NODE_IMAGE}
    container_name: mode-op-node
    command:
      - op-node
    env_file: .env
    ports:
      - ${RPC_BIND_ADDR}:${OP_NODE_RPC_PORT}:${OP_NODE_RPC_PORT}
      - ${OP_NODE_P2P_PORT}:${OP_NODE_P2P_PORT}
      - ${OP_NODE_P2P_PORT}:${OP_NODE_P2P_PORT}/udp
    volumes:
      - ${HOST_OP_NODE_DATADIR:-$HOME/mode-op-node-data}:/data
      - ./config:/config
    restart: unless-stopped
    depends_on:
      mode-op-reth:
        condition: service_started
    networks:
      - mode-network

networks:
  mode-network:
    driver: bridge
