#!/bin/sh

NODE_BIN=${NODE_BINARY:-morphnode}
NODE_HOME=${NODE_HOME:-/db}
JWT_PATH=${JWT_SECRET_PATH:-/config/jwt.hex}

export MORPH_NODE_L2_ETH_RPC=${MORPH_NODE_L2_ETH_RPC:-http://localhost:8545}
export MORPH_NODE_L2_ENGINE_RPC=${MORPH_NODE_L2_ENGINE_RPC:-http://localhost:8551}
export MORPH_NODE_L2_ENGINE_AUTH=${MORPH_NODE_L2_ENGINE_AUTH:-${JWT_PATH}}

export MORPH_NODE_L1_ETH_RPC=${MORPH_NODE_L1_ETH_RPC:-${L1_ETH_RPC:-}}
export MORPH_NODE_ROLLUP_ADDRESS=${MORPH_NODE_ROLLUP_ADDRESS:-${ROLLUP_CONTRACT:-}}
export MORPH_NODE_SYNC_START_HEIGHT=${MORPH_NODE_SYNC_START_HEIGHT:-${L1_MSG_START_HEIGHT:-}}
export MORPH_NODE_L1_CHAIN_ID=${MORPH_NODE_L1_CHAIN_ID:-${L1_CHAIN_ID:-}}

exec "${NODE_BIN}" \
  --home "${NODE_HOME}" \
  --log.filename "${NODE_HOME}/node.log" \
  ${NODE_EXTRA_FLAGS:-}
