services:
  soneium-op-reth:
    image: ${OP_RETH_IMAGE}
    container_name: soneium-op-reth
    command:
      - node
      - --chain=soneium
      - --storage.v2
      - --datadir=/data
      - --rollup.sequencer-http=https://rpc.soneium.org
      - --rollup.historicalrpc=https://rpc.soneium.org
      - --rollup.disable-tx-pool-gossip
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=web3,debug,eth,txpool,net
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=web3,debug,eth,txpool,net
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=9551
      - --authrpc.jwtsecret=/config/jwt.hex
      - --nat=extip:${EXT_IP}
      - --port=${RETH_PORT}
      - --metrics=127.0.0.1:9001
    volumes:
      - $HOME/soneium-op-reth-data:/data
      - ./config:/config
    ports:
      - 127.0.0.1:8241:8545
      - 127.0.0.1:8242:8546
      - ${RETH_PORT}:${RETH_PORT}
      - ${RETH_PORT}:${RETH_PORT}/udp
    restart: unless-stopped
    stop_grace_period: 120s
    networks:
      - soneium-network

  soneium-op-node:
    image: ${OP_NODE_IMAGE}
    container_name: soneium-op-node
    command:
      - op-node
    env_file: .env
    volumes:
      - $HOME/soneium-op-node-data:/data
      - ./config:/config
    restart: unless-stopped
    depends_on:
      soneium-op-reth:
        condition: service_started
    networks:
      - soneium-network

networks:
  soneium-network:
    driver: bridge
