[program:movarest]
command=sh -c "sleep 10 && exec movacli rest-server --unsafe-cors=true --savetx --home /data/clicfg --read-timeout %(ENV_READ_TIMEOUT)s --write-timeout %(ENV_WRITE_TIMEOUT)s --laddr tcp://0.0.0.0:8545 --wsaddr 0.0.0.0:8546 --grpc-node tcp://127.0.0.1:26680 --chain-id %(ENV_CHAIN_ID)s --rpc-api %(ENV_RPC_API)s"
priority=1000
autostart=true
autorestart=true
startsecs=15
startretries=100
stdout_logfile=/data/stdout-movarest.txt
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=3
stderr_logfile=/data/stderr-movarest.txt
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3
