[supervisord]
nodaemon=true
pidfile=/data/supervisord.pid
logfile=/data/supervisord.log
childlogdir=/data

[unix_http_server]
file=/data/supervisor.sock

[supervisorctl]
serverurl=unix:///data/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[include]
files = /etc/supervisor/conf.d/*.conf
